module.exports = {
  ALL_ACCOUNTS: 'ALL_ACCOUNTS',
  EDIT_ACCOUNT: 'EDIT_ACCOUNT',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_CAMPAIGN: 'CREATE_CAMPAIGN',
  REMOVE_ACCOUNT: 'CREATE_ACCOUNT',
  SINGLE_ACCOUNT: 'SINGLE_ACCOUNT',
  LOGIN: 'LOGIN',
  LOGIN_REG: 'LOGIN_REG',
  LOGIN_ER:"LOGIN_ER",
  LOGOUT:'LOGOUT',
  LOGIN_REDIR:'LOGIN_REDIR',
  ACCOUNTSDATA:'ALL_ACCOUNTS',
  ALL_USERS:'ALL_USERS'
};
